// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASXnYy8LK4FM0vSU6qZ74hFxTMZd7CHGU',
    appId: '1:927772126724:web:591d41fc5804efecd9cf51',
    messagingSenderId: '927772126724',
    projectId: 'pet-clinic-308c9',
    authDomain: 'pet-clinic-308c9.firebaseapp.com',
    databaseURL: 'https://pet-clinic-308c9-default-rtdb.firebaseio.com',
    storageBucket: 'pet-clinic-308c9.appspot.com',
    measurementId: 'G-KQ7EBTRV23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx9TVzeDukmX4L1cVO7Yyv-MKWxBEocwE',
    appId: '1:927772126724:android:db5f9383f8109badd9cf51',
    messagingSenderId: '927772126724',
    projectId: 'pet-clinic-308c9',
    databaseURL: 'https://pet-clinic-308c9-default-rtdb.firebaseio.com',
    storageBucket: 'pet-clinic-308c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHsLwrk6_NTm3vV7V1P6j-dmjHk_UYAAc',
    appId: '1:927772126724:ios:a4dcd8c212436bb8d9cf51',
    messagingSenderId: '927772126724',
    projectId: 'pet-clinic-308c9',
    databaseURL: 'https://pet-clinic-308c9-default-rtdb.firebaseio.com',
    storageBucket: 'pet-clinic-308c9.appspot.com',
    iosBundleId: 'com.example.appPetClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHsLwrk6_NTm3vV7V1P6j-dmjHk_UYAAc',
    appId: '1:927772126724:ios:a4dcd8c212436bb8d9cf51',
    messagingSenderId: '927772126724',
    projectId: 'pet-clinic-308c9',
    databaseURL: 'https://pet-clinic-308c9-default-rtdb.firebaseio.com',
    storageBucket: 'pet-clinic-308c9.appspot.com',
    iosBundleId: 'com.example.appPetClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASXnYy8LK4FM0vSU6qZ74hFxTMZd7CHGU',
    appId: '1:927772126724:web:07fbaae70f633023d9cf51',
    messagingSenderId: '927772126724',
    projectId: 'pet-clinic-308c9',
    authDomain: 'pet-clinic-308c9.firebaseapp.com',
    databaseURL: 'https://pet-clinic-308c9-default-rtdb.firebaseio.com',
    storageBucket: 'pet-clinic-308c9.appspot.com',
    measurementId: 'G-YMSNLFEE84',
  );
}
